name: "Setup Rust Environment"
description: "Install OpenSSL/pkg-config per OS and export env vars used by openssl-sys"
inputs:
  os:
    description: "Runner OS (ubuntu-latest | macos-latest | windows-latest)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install OS dependencies (Linux)
      if: startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Install OS dependencies (macOS)
      if: startsWith(inputs.os, 'macos')
      shell: bash
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: |
        brew install openssl@3 pkg-config
        OSSL_PATH=$(brew --prefix openssl@3)
        echo "PKG_CONFIG_PATH=$OSSL_PATH/lib/pkgconfig" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$OSSL_PATH/include" >> $GITHUB_ENV
        echo "LDFLAGS=-L$OSSL_PATH/lib" >> $GITHUB_ENV

    - name: Install OS dependencies (Windows)
      if: startsWith(inputs.os, 'windows')
      shell: powershell
      run: |
        choco install -y openssl --params "/NoTools"
        "OPENSSL_DIR=C:\Program Files\OpenSSL-Win64"        | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "OPENSSL_NO_PKG_CONFIG=1"                           | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "OPENSSL_LIB_DIR=C:\Program Files\OpenSSL-Win64\lib"| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL-Win64\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
