/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns a hello world message from the Specado core library. */
export declare function helloWorld(): string
/** Returns the version of the Specado library. */
export declare function version(): string
/** A more complex example showing async support */
export declare function helloWorldAsync(): Promise<string>
