/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Returns a hello world message from the Specado core library.
 */
export function helloWorld(): string

/**
 * Returns the version of the Specado library.
 */
export function version(): string

/**
 * A more complex example showing async support
 */
export function helloWorldAsync(): Promise<string>