name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  # Test Rust core library
  test-rust:
    name: Test Rust Core
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy -p specado-core -- -D warnings
      
      - name: Build core
        run: cargo build -p specado-core --verbose
      
      - name: Test core
        run: cargo test -p specado-core --verbose

  # Build and test Python bindings (separate from Rust tests)
  test-python:
    name: Test Python Bindings
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      
      - name: Install maturin
        run: |
          python -m pip install --upgrade pip
          pip install maturin
      
      - name: Build Python module
        working-directory: specado-python
        run: maturin build
      
      - name: Test Python FFI
        working-directory: specado-python
        run: |
          pip install target/wheels/*.whl
          python test_specado.py

  # Build and test Node.js bindings
  test-node:
    name: Test Node.js Bindings  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install dependencies
        working-directory: specado-node
        run: |
          npm install
          npm install -g @napi-rs/cli
      
      - name: Build Node module
        working-directory: specado-node
        run: npm run build:debug
      
      - name: Test Node FFI
        working-directory: specado-node  
        run: npm test